###########################################################################################################################################################################
# VENN DIAGRAMS
# Script to create Venn Diagrams for comparing two data sets of differential expressed genes.
# To create the Venn Diagram, you need two .csv files with z-scores and the differential expression status. 
# This script will produce: 
#       - Venn diagrams with all possible combinations
#       - a file containing a table showing overlaps of all possible combinations as an overview
#       - a file containing the names of the genes that are classified in the same group in both samples
###########################################################################################################################################################################
      start_time <- Sys.time()

# 1)  SET YOU WORKING DIRECTORY. This is where your input file is located and the results will be stored.
#     Click in the menubar on the tab "Session" > "Set Working Directory" > "Choose Directory..."
#     Then choose the directory where your input file (the one with the means) is located and the results will be stored.



# 2)  READ/IMPORT your file into RStudio. DEFINE the names of the two data sets that are compared and choose colours for them. These will be displayed in the Venn diagram.
#     Colours can be chosen from http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
#     This script requires two "*_z_scores.csv" files generated by the script "differential_gene_expression_analysis.R".

      input_file_1 <- read.csv("your_z_scores_raw_1.csv") # Type in here the name of the first file
      category_name_1 <- "sample_1"
      category_name_1_colour <- "slategray2"
        
      input_file_2 <- read.csv("your_z_scores_raw_1.csv") # Type in here the name of the first file
      category_name_2 <- "sample_2"
      category_name_2_colour <- "midnightblue"
      
      
      
# 3)  DEFINE how the numbers in the Venn diagram should be presented. Choose between "raw" or "percent".
      
      print_mode <- "raw"
      
  
      
# 4)  DEFINE if the size of the circles should be scaled depending on the number. Choose between TRUE or FALSE.      
          
      scaling <- FALSE
      
      
      
# 5)  DEFINE font sizes and fontfaces for the category names and the numbers visualized in the Venn diagram.
#     If you don't want to use these options and use the default, just write NULL instead of a number or the fontface type for the variable you don't
#     want to use. 
      
      # Set the size for names in the Venn diagram. Recommended: a number between 1 and 2
      category_name_font_size <- NULL
      # Set the size for numbers in the Venn diagram. Recommended: a number between 1 and 3
      numbers_font_size <- NULL
      
      # Set the fontface for the names in the Venn diagram. Choose either "bold" or "plain".
      category_name_fontface <- NULL
      # Set the fontface for the numbers in the Venn diagram. Choose either "bold" or "plain".
      numbers_fontface <- NULL
      
      
      
# 6)  NAME your output files/plots. The name should be as SHORT as possible. 
#     All relevant information about the results will be put in the file name automatically. 
      
      output_name <- "your_output_name"  # Type here the desired name of the output
      
      
      
# 7)  LET THE SCRIPT DO THE REST  
#     Highlight all code (Ctrl + A) and press Ctrl + Enter.
#     Plots and files will be saved automatically in a new directory in your working directory.
      
      
      
      
      
      
###########################################################################################################################################################################  
###########################################################################################################################################################################
# DON'T CHANGE ANYTHING IN HERE
      
      
      # CREATE A NEW DIRECTORY where the results will be stored.
      dir_name <- paste(Sys.Date(), "_", output_name, "_results_venn_diagrams", sep = "")
      ifelse(!dir.exists(dir_name), dir.create(dir_name), FALSE)
      results_dir <- file.path(getwd(), dir_name)
      Sys.chmod(results_dir, mode = "0777", use_umask = TRUE)
      setwd(results_dir)
      
      
      if (is.null(category_name_1_colour)) {category_name_1_colour <- "blue"}
      if (is.null(category_name_2_colour)) {category_name_2_colour <- "red"}
      
      if (is.null(category_name_font_size)) {category_name_font_size <- 1.5}
      if (is.null(numbers_font_size)) {numbers_font_size <- 2.5}
      if (is.null(category_name_fontface)) {category_name_fontface <- "bold"}
      if (is.null(numbers_fontface)) {numbers_fontface <- "bold"}
      
      category_colours <- c(category_name_1_colour, category_name_2_colour)
      category_names <- c(category_name_1, category_name_2)
      
      
#####################################################################################################################  
# GENERATE VENN DIAGRAMS FOR ALL DIFFERENTIALLY EXPRESSED GENES #####################################################
#####################################################################################################################
      
      library(futile.logger)
      # suppress logging messages of "VennDiagram"
      futile.logger::flog.threshold(futile.logger::ERROR, name = "VennDiagramLogger")
      
      library(VennDiagram)
      
      if (nrow(input_file_2) > nrow(input_file_1)) rotation.deg <- 180 else rotation.deg <- 0
      
      VennDiagram::venn.diagram(x=list(input_file_1[, "gene"], input_file_2[, "gene"]), category.names = c(category_name_1, category_name_2), filename = paste(category_name_1, "_", category_name_2, ".png", sep = ""), output = TRUE ,
                                imagetype="png",
                                # main = main_title,
                                # main.fontface = "bold",
                                # main.fontfamily = "sans",
                                rotation.degree = rotation.deg,
                                scaled = scaling,
                                width = 3000,
                                height = 3000,
                                resolution = 600,
                                compression = "lzw",
                                lwd = 2,
                                lty = 'blank',
                                fill = category_colours,
                                cex = numbers_font_size, # size of numbers in circle 
                                fontface = numbers_fontface, # numbers in circle: "bold" or "plain"
                                fontfamily = "sans",
                                #fontsize = 50,
                                cat.cex = category_name_font_size, # size of category names
                                cat.fontface = category_name_fontface, # category names in circle: "bold" or "plain"
                                cat.default.pos = "outer",
                                cat.pos = c(0, 0),
                                cat.dist = c(0.055, 0.055),
                                cat.fontfamily = "sans",
                                print.mode = print_mode
                                
      )
      
      
      
#####################################################################################################################  
# GENERATE VENN DIAGRAMS FOR ALL COMBINATIONS OF DIFFERENTIAL EXPRESSION STATUS #####################################
#####################################################################################################################
      
      de_status_1 <- as.vector(unique(input_file_1$differential.expression))
      de_status_2 <- as.vector(unique(input_file_2$differential.expression))
      
      
      for (i in de_status_1) {
          for (j in de_status_2) {
              
              de_status_data_1 <- input_file_1[input_file_1$differential.expression== i, "gene"]
              de_status_data_2 <- input_file_2[input_file_2$differential.expression== j, "gene"]
              
              if (length(input_file_2[input_file_2$differential.expression== j, "gene"]) > length(input_file_1[input_file_1$differential.expression== i, "gene"])) rotation.deg <- 180 else rotation.deg <- 0
              
              VennDiagram::venn.diagram(x=list(de_status_data_1, de_status_data_2), category.names = c(category_name_1, category_name_2), filename = paste(category_name_1, "_", gsub("[[:punct:]]|\\s", "transient.", i), "_", category_name_2, "_", gsub("[[:punct:]]|\\s", "transient.", j), ".png", sep = ""), output = TRUE ,
                                        imagetype="png",
                                        # main = main_title,
                                        # main.fontface = "bold",
                                        # main.fontfamily = "sans",
                                        rotation.degree = rotation.deg,
                                        scaled = scaling,
                                        width = 3000,
                                        height = 3000,
                                        resolution = 600,
                                        compression = "lzw",
                                        lwd = 2,
                                        lty = 'blank',
                                        fill = category_colours,
                                        cex = numbers_font_size, # size of numbers in circle 
                                        fontface = numbers_fontface, # numbers in circle: "bold" or "plain"
                                        fontfamily = "sans",
                                        #fontsize = 50,
                                        cat.cex = category_name_font_size, # size of category names
                                        cat.fontface = category_name_fontface, # category names in circle: "bold" or "plain"
                                        cat.default.pos = "outer",
                                        cat.pos = c(0, 0),
                                        cat.dist = c(0.055, 0.055),
                                        cat.fontfamily = "sans",
                                        print.mode = print_mode
                                        
              )
          }
      }
      
      
      
      
#####################################################################################################################  
# GENERATE COMPARISON TABLE AND TABLE WITH NAMES OF OVERLAPPING GENES ###############################################
#####################################################################################################################
      
      library(xlsx)
      
# COMPARISON TABLE
      transient_up_1 <- input_file_1[input_file_1$differential.expression=="*up", "gene"]
      transient_down_1 <- input_file_1[input_file_1$differential.expression=="*down", "gene"]
      transition_up_1 <- input_file_1[input_file_1$differential.expression=="up", "gene"]
      transition_down_1 <- input_file_1[input_file_1$differential.expression=="down", "gene"]
      
      transient_up_2 <- input_file_2[input_file_2$differential.expression=="*up", "gene"]
      transient_down_2 <- input_file_2[input_file_2$differential.expression=="*down", "gene"]
      transition_up_2 <- input_file_2[input_file_2$differential.expression=="up", "gene"]
      transition_down_2 <- input_file_2[input_file_2$differential.expression=="down", "gene"]
      
      
      overlap_transition_up_transition_up <- VennDiagram::calculate.overlap(list(transition_up_1, transition_up_2))
      overlap_transition_up_transition_down <- VennDiagram::calculate.overlap(list(transition_up_1, transition_down_2))
      overlap_transition_up_transient_up <- VennDiagram::calculate.overlap(list(transition_up_1, transient_up_2))
      overlap_transition_up_transient_down <- VennDiagram::calculate.overlap(list(transition_up_1, transient_down_2))
      
      transition_ups <- c(length(overlap_transition_up_transition_up$a3),
                             length(overlap_transition_up_transition_down$a3),
                             length(overlap_transition_up_transient_up$a3),
                             length(overlap_transition_up_transient_down$a3))
      
      
      overlap_transition_down_transition_up <- VennDiagram::calculate.overlap(list(transition_down_1, transition_up_2))
      overlap_transition_down_transition_down <- VennDiagram::calculate.overlap(list(transition_down_1, transition_down_2))
      overlap_transition_down_transient_up <- VennDiagram::calculate.overlap(list(transition_down_1, transient_up_2))
      overlap_transition_down_transient_down <- VennDiagram::calculate.overlap(list(transition_down_1, transient_down_2))
      
      transition_downs <- c(length(overlap_transition_down_transition_up$a3),
                               length(overlap_transition_down_transition_down$a3),
                               length(overlap_transition_down_transient_up$a3),
                               length(overlap_transition_down_transient_down$a3))
      
      
      
      overlap_transient_up_transition_up <- VennDiagram::calculate.overlap(list(transient_up_1, transition_up_2))
      overlap_transient_up_transition_down <- VennDiagram::calculate.overlap(list(transient_up_1, transition_down_2))
      overlap_transient_up_transient_up <- VennDiagram::calculate.overlap(list(transient_up_1, transient_up_2))
      overlap_transient_up_transient_down <- VennDiagram::calculate.overlap(list(transient_up_1, transient_down_2))
      
      transient_ups <- c(length(overlap_transient_up_transition_up$a3),
                            length(overlap_transient_up_transition_down$a3),
                            length(overlap_transient_up_transient_up$a3),
                            length(overlap_transient_up_transient_down$a3))
      
      
      
      overlap_transient_down_transition_up <- VennDiagram::calculate.overlap(list(transient_down_1, transition_up_2))
      overlap_transient_down_transition_down <- VennDiagram::calculate.overlap(list(transient_down_1, transition_down_2))
      overlap_transient_down_transient_up <- VennDiagram::calculate.overlap(list(transient_down_1, transient_up_2))
      overlap_transient_down_transient_down <- VennDiagram::calculate.overlap(list(transient_down_1, transient_down_2))
      
      transient_downs <- c(length(overlap_transient_down_transition_up$a3),
                              length(overlap_transient_down_transition_down$a3),
                              length(overlap_transient_down_transient_up$a3),
                              length(overlap_transient_down_transient_down$a3))
      
      
      comparison_table <- data.frame(transition_ups, transition_downs, transient_ups, transient_downs)
      colnames(comparison_table) <-  c(paste(gsub("[[:punct:]]|\\s", ".", category_names[1]), "_up", sep = ""), 
                                       paste(gsub("[[:punct:]]|\\s", ".", category_names[1]), "_down", sep = ""),
                                       paste(gsub("[[:punct:]]|\\s", ".", category_names[1]), "_transient_up", sep = ""),
                                       paste(gsub("[[:punct:]]|\\s", ".", category_names[1]), "_transient_down", sep = ""))
      
      
      rownames(comparison_table) <- c(paste(gsub("[[:punct:]]|\\s", ".", category_names[2]), "_up", sep = ""), 
                                      paste(gsub("[[:punct:]]|\\s", ".", category_names[2]), "_down", sep = ""), 
                                      paste(gsub("[[:punct:]]|\\s", ".", category_names[2]), "_transient_up", sep = ""), 
                                      paste(gsub("[[:punct:]]|\\s", ".", category_names[2]), "_transient_down", sep = ""))
      
      write.xlsx(comparison_table, paste(output_name, "_comparison_table.xlsx", sep = ""))
      
      
      
# NAMES OF OVERLAPPING GENES
      comparison_de_genes <- plyr::rbind.fill(data.frame(t(data.frame(overlap_transition_up_transition_up$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ), 
                                              data.frame(t(data.frame(overlap_transition_up_transition_down$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transition_up_transient_up$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transition_up_transient_down$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              
                                              data.frame(t(data.frame(overlap_transition_down_transition_up$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transition_down_transition_down$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transition_down_transient_up$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transition_down_transient_down$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              
                                              data.frame(t(data.frame(overlap_transient_up_transition_up$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transient_up_transition_down$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transient_up_transient_up$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transient_up_transient_down$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              
                                              data.frame(t(data.frame(overlap_transient_down_transition_up$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transient_down_transition_down$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transient_down_transient_up$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE ),
                                              data.frame(t(data.frame(overlap_transient_down_transient_down$a3, stringsAsFactors = FALSE)), stringsAsFactors = FALSE )
                                              
      )
      
      rownames(comparison_de_genes) <- gsub("[[:punct:]]|\\s", ".", paste(rep(category_names[1], 4), rep(c("up", "down", "transient.up", "transient.down"), each=4), category_names[2], rep(c("up", "down", "transient.up", "transient.down"), 4)))
      comparison_de_genes <- data.frame(t(comparison_de_genes), stringsAsFactors = FALSE)
      write.xlsx(comparison_de_genes, paste(output_name, "comparison_de_genes.xlsx"))
      
      end_time <- Sys.time()
      
      
      
      
      
      paste("Total time consumed for the analysis:", round(end_time - start_time, 2), attr((end_time - start_time), "unit")) 