###########################################################################################################################################################################
# SUBSEQUENT ANALYSIS OF THE CORRELATION
# Script to analyse the correlation coefficients for two time series data sets further.
# To do the analysis, you need a .csv file with a correlation matrix as input. 
# This script will produce: 
#       - a heatmap of selected substances and genes with a file containing the correlation coefficients
#       - a file containing the x highest correlation coefficients in the whole matrix
#       - a file containing the x highest correlation coefficients in a selected row or column
#       - a file containing correlation coefficients above a selected threshold in the whole matrix
#       - a file containing correlation coefficients above a selected threshold in a selected row or column
###########################################################################################################################################################################
      start_time <- Sys.time()

# 1)  SET YOU WORKING DIRECTORY. This is where your input file is located and the results will be stored.
#     Click in the menubar on the tab "Session" > "Set Working Directory" > "Choose Directory..."
#     Then choose the directory where your input file (the one with the means) is located and the results will be stored.



# 2)  READ/IMPORT your file into RStudio.
#     This script requires the "*_correlation_matrix.csv" file generated by the script "correlation.R".
#     Watch out! The row and column names should not contain any special characters!

      input_file <- read.csv("your_correlation_matrix.csv", check.names = FALSE) # Type in here the name of the file
      
      data_type_row <- "sample_1"
      data_type_col <- "sample_2"
      
      
      
# 3)  DEFINE of which selected rows and columns you want to retrieve the correlation coefficients.
#     Keep in mind that you define by this the rows and columns that should be evaluated, so watch out defining the rows and columns right.
#     Furthermore, it is possible to select only rows, only columns or none rows or columns. 
#     If you don't want to select specific rows or columns: write NULL as the value for either one or both variables.
      
      selected_rows <- c("substance_1", 
                         "substance_2", 
                         "substance_3")
      
      selected_cols <- c("gene_1",
                         "gene_2",
                         "gene_3",
                         "gene_5",
                         "gene_6")
      
   
      
# 4) DEFINE font sizes for row and column titles, names, the legend title, legend lables and the size of the legend bar in the heatmap.       
#    If you don't want to use these options and use the default, just write NULL instead of a number for the variable you don't
#    want to use.
      
      # Set the font sizes
      heatmap_row_column_title_font_size <- NULL
      heatmap_row_column_name_font_size <- NULL
      legend_title_font_size <- NULL
      legend_label_font_size <- NULL
      
      # Set the size of the legend bar (in points)
      legend_height <- NULL
      
      
      
# 5)  DEFINE whether you want to retrieve the x highest correlation coefficients of the whole correlation matrix and/or the selected rows/columns.
#     The numbers will be processed independently, so you can choose both, only one or even none of them.
#     If you don't want to retrieve the x highest correlation coefficients of the whole transcriptome or for selected rows/columns: write NULL as
#     the value for either one or both variables.
      
      number_of_highest_correlation_coefficients <- NULL
      
      number_of_highest_correlation_coefficients_selected <- NULL
      
      

# 6)  DEFINE the threshold of the correlation coefficients for the whole correlation matrix and the selected rows/columns you want to retrieve.
#     The numbers will be processed independently, so you can choose both, only one or even none of them.
#     If you don't want to retrieve the correlation coefficients above a specific threshold for the whole transcriptome or for selected rows/columns: write NULL as
#     the value for either one or both variables.
#     Recommended: start with a value of 0.7 or 0.8 on big data sets      
      
      threshold <- NULL
      
      threshold_selected <- NULL
      
      
      
# 7)  NAME your output files/plots. The name should be as SHORT as possible. 
#     All relevant information about the results will be put in the file name automatically. 
      
      output_name <- "your_output_name"  # Type here the desired name of the output
      
      
      
# 8)  LET THE SCRIPT DO THE REST  
#     Highlight all code (Ctrl + A) and press Ctrl + Enter.
#     Plots and files will be saved automatically in a new directory in your working directory.
      
      
      
      
      
      
###########################################################################################################################################################################  
###########################################################################################################################################################################
# DON'T CHANGE ANYTHING IN HERE
      
      
# CREATE A NEW DIRECTORY where the results will be stored.
      dir_name <- paste(Sys.Date(), "_", output_name, "_results_subsequent_correlation_analysis", sep = "")
      ifelse(!dir.exists(dir_name), dir.create(dir_name), FALSE)
      results_dir <- file.path(getwd(), dir_name)
      Sys.chmod(results_dir, mode = "0777", use_umask = TRUE)
      setwd(results_dir)
     
      
# FORMAT the input file and selected row and col names
      rownames(input_file) <- input_file[,1]
      input_file <- input_file[,-1]
      input_file <- as.matrix(input_file)
      

      if (is.null(heatmap_row_column_title_font_size)) {heatmap_row_column_title_font_size <- 20}
      if (is.null(heatmap_row_column_name_font_size)) {heatmap_row_column_name_font_size <- 15}
      if (is.null(legend_title_font_size)) {legend_title_font_size <- 20}
      if (is.null(legend_label_font_size)) {legend_label_font_size <- 15}
      if (is.null(legend_height)) {legend_height <- 200}
      
      
      # Checking if all selected rows are present in the correlation matrix
      if (!is.null(selected_rows)) {
          rows_not_in_set <- selected_rows[which(!is.element(selected_rows, rownames(input_file)))]
          selected_rows <- selected_rows[which(is.element(selected_rows, rownames(input_file)))]
          
          # If not: write a file they were excluded, because all timepoints are zero
          if (length(rows_not_in_set) != 0) {
              sink(paste(output_name, "_selected_rows.txt", sep = ""))
              print("Some of your ’selected_rows’ were not found in the correlation matrix.")
              print("Their expression is all zero, so they were excluded from the file containing means.")
              print("The excluded selected rows were:")
              print(rows_not_in_set)
              sink()
          }
          
      }
      
      # Checking if all selected cols are present in the correlation matrix
      if (!is.null(selected_cols)) {
          cols_not_in_set <- selected_cols[which(!is.element(selected_cols, colnames(input_file)))]
          selected_cols <- selected_cols[which(is.element(selected_cols, colnames(input_file)))]
          
          # If not: write a file they were excluded, because all timepoints are zero
          if (length(cols_not_in_set) != 0) {
              sink(paste(output_name, "_selected_cols.txt", sep = ""))
              print("Some of your ’selected_cols’ were not found in the correlation matrix.")
              print("Their expression is all zero, so they were excluded from the file containing means.")
              print("The excluded selected columns were:")
              print(cols_not_in_set)
              sink()
          }
          
      }

      library(xlsx)
      
#####################################################################################################################  
# RETRIEVE X HIGHEST CORRELATION COEFFICIENTS OF THE WHOLE MATRIX ###################################################
#####################################################################################################################
     
      if (!is.null(number_of_highest_correlation_coefficients)) {
      
      # Create long correlation matrix data frame:
      long_correlation <- data.frame(row = rep(rownames(input_file), ncol(input_file)), col = rep(colnames(input_file), each = nrow(input_file)),
                                     correlation.coefficient = as.vector(input_file))
      colnames(long_correlation) <- c(data_type_row, data_type_col, "correlation.coefficient")
      # Sort the correlation coefficients from highest to lowest
      ordered_long_correlation <- long_correlation[rev(order(long_correlation$correlation.coefficient, na.last = FALSE)), ]
      rownames(ordered_long_correlation) <- 1:nrow(ordered_long_correlation)
      # Get x highest correlation coefficients
      write.xlsx(ordered_long_correlation[1:number_of_highest_correlation_coefficients, ], paste(output_name, "_", as.character(number_of_highest_correlation_coefficients), "_highest_correlation_coefficients.xlsx", sep = ""))
   
      } 
    
      
#####################################################################################################################  
# RETRIEVE X HIGHEST CORRELATION COEFFICIENTS OF SELECTED ROWS AND COLUMNS ##########################################
#####################################################################################################################
     
      # Get x highest correlation coefficients for a specific gene row
      if (!is.null(selected_rows) && !is.null(number_of_highest_correlation_coefficients_selected)) {
        
          rows_not_in_set <- selected_rows[which(!is.element(selected_rows, rownames(input_file)))]
          selected_rows <- selected_rows[which(is.element(selected_rows, rownames(input_file)))]
      
          for (i in 1:length(selected_rows)) {
            
              temp_df <- data.frame(input_file[selected_rows[i], order(input_file[selected_rows[i], ], decreasing = TRUE)][1:number_of_highest_correlation_coefficients_selected])
              colnames(temp_df) <- selected_rows[i]
              write.xlsx(temp_df, paste(output_name, "_", number_of_highest_correlation_coefficients_selected, "_highest_correlation_coefficients_for_", selected_rows[i], ".xlsx", sep = ""))
          
          }
      
      }
      
      
      # Get x highest correlation coefficients for a selected column
      if (!is.null(selected_cols) && !is.null(number_of_highest_correlation_coefficients_selected)) {
      
          for (i in 1:length(selected_cols)) {
            
              temp_df <- data.frame(input_file[order(input_file[, selected_cols[i]], decreasing = TRUE), selected_cols[i]][1:number_of_highest_correlation_coefficients_selected])
              rownames(temp_df) <- rownames(input_file)[order(input_file[, selected_cols[i]], decreasing = TRUE)][1:number_of_highest_correlation_coefficients_selected]
              colnames(temp_df) <- selected_cols[i]
              write.xlsx(temp_df, paste(output_name, "_", number_of_highest_correlation_coefficients_selected, "_highest_correlation_coefficients_for_", selected_cols[i], ".xlsx", sep = ""))
              
          }
      
      }

      
      
#####################################################################################################################  
# RETRIEVE CORRELATION COEFFICIENTS OF SELECTED ROWS AND COLUMNS ABOVE A SPECIFIC THRESHOLD #########################
#####################################################################################################################
      
      if (!is.null(threshold)){
        
          above_threshold <- ordered_long_correlation[which(ordered_long_correlation[,3] > threshold),]
          write.xlsx(above_threshold, paste(output_name, "_correlation coefficients_r", threshold, ".xlsx", sep = ""))
          
      }
            
      
#####################################################################################################################  
# RETRIEVE CORRELATION COEFFICIENTS OF THE WHOLE MATRIX ABOVE A SPECIFIC THRESHOLD ##################################
#####################################################################################################################
      
      # Get correlation coefficients above a defined threshold for a specific row
      if (!is.null(selected_rows) && !is.null(threshold_selected)) {
      
          for (i in 1:length(selected_rows)) {
            
              temp_df <- data.frame(input_file[selected_rows[i], which(input_file[selected_rows[i],] > threshold_selected)])
              colnames(temp_df) <- selected_rows[i]
              temp_df_ordered <- data.frame(temp_df[order(temp_df, decreasing = TRUE),])
              colnames(temp_df_ordered) <- selected_rows[i]
              row.names(temp_df_ordered) <- rownames(temp_df)[order(temp_df, decreasing = TRUE)]
              
              if (nrow(temp_df) != 0) {
                
                  write.xlsx(temp_df, paste(output_name, "_", selected_rows[i], "_correlation_coefficients_r", threshold_selected, ".xlsx", sep = ""))
              
              }
              
          }
        
      }
      
      
      # Get correlation coefficients above a defined threshold for a specific column
      if (!is.null(selected_cols) && !is.null(threshold_selected)) {
      
          for (i in 1:length(selected_cols)) {
            
              temp_df <- data.frame(input_file[which(input_file[, selected_cols[i]] > threshold_selected), selected_cols[i]])
              colnames(temp_df) <- selected_cols[i]
              row.names(temp_df) <- rownames(input_file)[which(input_file[, selected_cols[i]] > threshold_selected)]
              
              if (nrow(temp_df) != 0) {
              
                  temp_df_ordered <- temp_df[order(selected_cols[i])]
                  colnames(temp_df_ordered) <- selected_cols[i]
                  row.names(temp_df_ordered) <- rownames(temp_df)[order(temp_df, decreasing = TRUE)]
                  write.xlsx(temp_df, paste(output_name, "_", selected_cols[i], "_correlation_coefficients_r", threshold_selected, ".xlsx", sep = ""))
            
              }
              
          }
      
      }
      
      
#####################################################################################################################  
# RETRIEVE CORRELATION COEFFICIENTS OF COMBINED SELECTED ROWS AND COLUMNS ###########################################
#####################################################################################################################
      
      
      
      # Get correlation coefficients from combining selected rows and selected columns
      if (!is.null(selected_rows) && !is.null(selected_cols)) {
        
          selected_coeffs <- data.frame(input_file[selected_rows, selected_cols], check.names = FALSE)
      
          if (length(selected_cols) == 1) {
            
              rownames(selected_coeffs) <- selected_rows
              colnames(selected_coeffs) <- selected_cols
              
            
          } else if (length(selected_rows) == 1) {
            
            selected_coeffs <- data.frame(t(selected_coeffs))
            rownames(selected_coeffs) <- selected_rows
            colnames(selected_coeffs) <- selected_cols
            
          }
        
          
          selected_coeffs <- as.matrix(selected_coeffs)
    
          library(ComplexHeatmap)
          library(circlize)
          selected_heatmap <- Heatmap(selected_coeffs, 
                                      heatmap_legend_param = list(title = "Correlation coefficient", title_gp =gpar(fontsize = legend_title_font_size), labels_gp=gpar(fontsize = legend_label_font_size), legend_height=unit(legend_height, "points"), title_position="leftcenter-rot"),
                                      column_title = data_type_col,
                                      column_title_side = "top",
                                      column_title_gp = gpar(fontsize = heatmap_row_column_title_font_size),
                                      column_names_gp = gpar(fontsize = heatmap_row_column_name_font_size),
                                      row_title = data_type_row, 
                                      row_title_side = "left", 
                                      row_title_rot = 90, 
                                      row_title_gp = gpar(fontsize = heatmap_row_column_title_font_size),
                                      row_names_gp = gpar(fontsize = heatmap_row_column_name_font_size),
                                      show_row_names = TRUE, 
                                      show_column_names = TRUE,
                                      col = colorRamp2(c(-1, 0, 1), c("blue", "#EEEEEE", "red")))
          
          png(paste(output_name, "_correlation_heatmap_of_selected.png", sep = ""), width = 4800, height = 4800, res = 600)
          draw(selected_heatmap)
          dev.off()
      
          # Get order of substances (rows) and genes (columns) as ordered in heatmap
          colorder <- column_order(selected_heatmap)
          roworder <- row_order(selected_heatmap)
          
          # Turn list of orderes into vectors
          colorder_v <- unlist(colorder)
          roworder_v <- unlist(roworder)
          
          # Create a data frame with ordered substances and genes as in the heatmap
          ordered_correlation <- selected_coeffs[roworder_v, colorder_v]
          
          # Save ordered correlation matrix in a file
          write.xlsx(ordered_correlation, paste(output_name, "_correlation_heatmap_of_selected_", data_type_row, "_and_", data_type_col, ".xlsx", sep = ""))
          
          
      } 
      
      end_time <- Sys.time()
      
      
      
      
      
      paste("Total time consumed for the analysis:", round(end_time - start_time, 2), attr((end_time - start_time), "unit"))